// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommunicateClient is the client API for Communicate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunicateClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type communicateClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicateClient(cc grpc.ClientConnInterface) CommunicateClient {
	return &communicateClient{cc}
}

func (c *communicateClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/Communicate/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicateServer is the server API for Communicate service.
// All implementations must embed UnimplementedCommunicateServer
// for forward compatibility
type CommunicateServer interface {
	Apply(context.Context, *ApplyRequest) (*StatusResponse, error)
	mustEmbedUnimplementedCommunicateServer()
}

// UnimplementedCommunicateServer must be embedded to have forward compatible implementations.
type UnimplementedCommunicateServer struct {
}

func (UnimplementedCommunicateServer) Apply(context.Context, *ApplyRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedCommunicateServer) mustEmbedUnimplementedCommunicateServer() {}

// UnsafeCommunicateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunicateServer will
// result in compilation errors.
type UnsafeCommunicateServer interface {
	mustEmbedUnimplementedCommunicateServer()
}

func RegisterCommunicateServer(s grpc.ServiceRegistrar, srv CommunicateServer) {
	s.RegisterService(&Communicate_ServiceDesc, srv)
}

func _Communicate_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicateServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Communicate/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicateServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Communicate_ServiceDesc is the grpc.ServiceDesc for Communicate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Communicate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Communicate",
	HandlerType: (*CommunicateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _Communicate_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/communicate.proto",
}
